name: pop_pop_win
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  js: ^0.6.1
  stagexl: ^2.0.0

dev_dependencies:
  build_runner:
  build_web_compilers: ^3.0.0
  lints: ^1.0.0
  preload: ^2.0.0
  test: ^1.0.0
